baseURL = "https://glc.st/"
# baseURL = "http://glc.st.local.net/"
# googleAnalytics = "G-NRF716WMB7"
languageCode = "en-us"
title = "Gwendal Le Coguic"
theme = "coder"

defaultcontentlanguage = "en"

# paginate = 2000
pagination.pagerSize = 2000
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClassic = false

disqusShortname = ""

disableKinds = ['RSS']
# disableKinds = ['RSS','sitemap','taxonomy','term']

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  tag = "tags"

[params]
    author = "Gwendal Le Coguic"
    title = "Gwendal Le Coguic"
    twitter = "gwendallecoguic"
    # info = "independent cybersecurity expert"
    info = "Expert indépendant en cyber sécurité"
    description = "Gwendal Le Coguic, developer, bug hunter, independent cybersecurity expert"
    keywords = "developer,webapp,cybersecurity,researcher,pentest,bugbounty,cybertools,bash,php,python,golang,offsectools"
    avatarurl = "/assets/img/me.jpg"
#    avatarurl = "/assets/img/avatar.jpg"
    images = ["/assets/img/header-background.jpg"]

    favicon_256 = "/assets/img/favicon-256x256.png"
    favicon_128 = "/assets/img/favicon-128x128.png"
    favicon_64 = "/assets/img/favicon-64x64.png"
    favicon_32 = "/assets/img/favicon-32x32.png"
    favicon_16 = "/assets/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["/assets/css/custom.css"]
    custom_js = ["/assets/js/scripts.js","/assets/js/gtag.js"]

    disable_comments = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 3
    url = "https://github.com/gwen001/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/gwendal-le-coguic/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/gwendallecoguic/"

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 4
    url  = "/projects/"
[[menu.main]]
    name = "CVEs"
    weight = 5
    url  = "/cves/"
# [[menu.main]]
#     name = "Services"
#     weight = 4
#     url  = "/services/"
[[menu.main]]
    name = "Courses"
    weight = 2
    url  = "/courses/"
[[menu.main]]
    name = "Customers"
    weight = 3
    url  = "/customers/"
[[menu.main]]
    name = "Press"
    weight = 6
    url  = "/press/"
# [[menu.main]]
#     name = "About"
#     weight = 7
#     url = "/about/"


[permalinks]
  posts = "/posts/:title/"
